node : 
  - name: R1 
    images: ubuntu2004
    interface:
     - { name: eth0, type: direct, peer: R2-eth0 }
  - name: R2 
    images: ubuntu2004
    interface:
      - { name: eth0, type: direct, peer: R1-eth0 }
node_config:
  - name: R1 
    config:
     - { cmd : ip addr add 10.0.0.1/24 dev eth0 }
  - name: R2
    config:
     - { cmd : ip addr add 10.0.0.2/24 dev eth0 }
