FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y vim && \
    apt-get install -y iputils-ping && \
    apt-get install -y net-tools && \
    apt-get install -y iperf && \
    apt-get install -y iperf3 && \
    apt-get install -y iproute2 && \
    apt-get install -y tcpdump && \
    apt-get install -y inetutils-traceroute && \
    apt-get install -y traceroute

