node : 
  - name: R1 
    image: ubuntu2004
    interface:
      - { name: eth0, type: bridge, bridge_name: br0, peer: R1-eth0 }
  - name: R2 
    image: ubuntu2004
    interface:
      - { name: eth0, type: bridge, bridge_name: br0, peer: R2-eth0 }
  - name: R3 
    image: ubuntu2004
    interface:
      - { name: eth0, type: bridge, bridge_name: br0, peer: R3-eth0 }

node_config:
  - name: R1 
    config:
      - { cmd : ip addr add 10.0.0.1/24 dev eth0 }
  - name: R2
    config:
      - { cmd : ip addr add 10.0.0.2/24 dev eth0 }
  - name: R3
    config:
      - { cmd : ip addr add 10.0.0.3/24 dev eth0 }
