node : 
  - name: R1 
    image: ubuntu2004
    interface:
      - { name: eth0, type: direct, peer: R2-eth0 }
  - name: R2
    image: ubuntu200
    interface:
      - { name: eth0, type: direct, peer: R2-eth0 }

node_config:
  - name: R1 
    config:
      - { cmd : ip addr add 10.0.0.1/24 dev eth0 }
      - { cmd : ip route add 10.0.1.0/24 via 10.0.0.2 }
